### ISSUE TITLE
[Bug]: ENOTDIR: not a directory, lstat

### ISSUE THREAD

**Issue by felixmosh** [Platane/github-secret-dotenv#9]
Hi, I'm trying to update the lib to latest version (v1.1.0), using `yarn`, but I get this error when I install it.
```
error An unexpected error occurred: "ENOTDIR: not a directory, lstat '/Users/***/Projects/node/***/node_modules/github-secret-dotenv/lib/cli/commandList.js'".
```

Using Mac BigSur

**Comment by Platane** [comment]
v1.1.1 is released. lgtm, do you confirm ?

**Comment by felixmosh** [comment]
It is still reproduces, I suspect that it is related to the fact that the file is without an extension

**Comment by Platane** [comment]
executable binaries usually don't have extension 

can you check the content of your node_modules/github-secret-dotenv

I suspect a file permission issue (?)

**Comment by felixmosh** [comment]
it fails on install, so the package is not updated.
Other packages works as usual...

**Comment by Platane** [comment]
strange

I made a new ci test running on macos latest and it doesn't have issue install 
https://github.com/Platane/github-secret-dotenv/runs/1584327682?check_suite_focus=true

Could it be that I changed a file to a directory  ( lib/cli ) with 1.1.0 ? can you try to install from an empty project ?

**Comment by felixmosh** [comment]
You were right, clean install solved it, weird.
